config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :users

  resources :doctors
  resources :accounts
  resources :articles

  get 'admin_page/index'
  resources :medicines
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'


  get 'diagnoses/index'
  get 'homepage/index'
  
  root "homepage#index"

  get "/login",
    to: "home#index",
    as: "Home_index"

  get "/diagnoses",
    to: "diagnoses#index",
    as: "Diagnoses_index"

  post "/diagnoses/index",
    to: "diagnoses#result",
    as: "diagnoses_result"

  get "/article",
    to: "articles#user_index",
    as: "user_index_article"

  get "/medicine",
    to: "medicines#user_index",
    as: "user_index_medicine"

  get "/doctor",
    to: "doctors#user_index",
    as: "user_index_doctor"

end

app/models/account.rb
class Account < ApplicationRecord
  # adds virtual attributes for authentication
  has_one :user
  has_one :doctor
  has_many :meeting
  
  # validates email
  validates :username, presence: true, uniqueness: true
  # validates :username, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid username' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :account
  end

app/models/diagnoses.rb
class Diagnoses < ApplicationRecord
    has_many :answer

    validates :answer, presence: true
    validates :answer, uniqueness: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :account
end

app/models/medicine.rb
class Medicine < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord

  belongs_to :account
  
  def create_zoom_meeting(topic)
   zoom_client = Zoom.new
   response = zoom_client.meeting_create(topic: topic, user_id: "Em94MPQZTua6na9XpzRe5A")
   response['join_url']
  end
  def save_zoom_link(meeting_topic)
    return if zoom_link.present?
    _zoom_link = create_zoom_meeting(meeting_topic)
    update(zoom_link: _zoom_link)
  end


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit {broadcast_append_to "rooms"}
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :account
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.save_zoom_link(@meeting.tanggal)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:tanggal,:doctor,:account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tanggal, style: "display: block" %>
    <%= form.date_field :tanggal %>
  </div>

  <div>
    <%= form.label :dokter, style: "display: block" %>
    <%= form.text_field :doctor%>
  </div>
  <div>
    <%= form.hidden_field :account_id, value: Current.account.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/_meeting.html.erb
<div id="<%= dom_id meeting %>">
  <p>
    <strong>Tanggal:</strong>
    <%= meeting.tanggal %>
  </p>
  <p>
    <strong>Dokter:</strong>
    <%= meeting.doctor %>
  </p>
  <p>
    <strong>Zoom link:</strong>
    <%= link_to meeting.zoom_link, meeting.zoom_link%>

  </p>

</div>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Meetings</h1>

<div id="meetings">
  <% if Current.account.role == "DOKTER" %>
    <% @meet = Meeting.find(:all, :conditions => "doctor = Current.account.id") %>
  <% elsif Current.account.role == "user" %>
    <% @meet = Meeting.where(:account_id => Current.account.id) %>
  <% elsif Current.account.role == "admin" %>
    <% @meet = Meeting.all %>
  <% end %>

  <% if @meet %>
    <% @meet.each do |meeting| %>
      <%= render meeting %>
      <p>
        <%= link_to "Show this meeting", meeting %>
      </p>
    <% end %>
  <% else %>
    <h3> No meeting yet </h3>
  <%end%>
</div>

<%= link_to "New meeting", new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meeting %>

<div>
  <%= link_to "Edit this meeting", edit_meeting_path(@meeting) %> |
  <%= link_to "Back to meetings", meetings_path %>

  <%= button_to "Destroy this meeting", @meeting, method: :delete %>
</div>