config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :users

  resources :doctors
  resources :accounts
  resources :articles

  get 'admin_page/index'
  resources :medicines
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'


  get 'diagnoses/index'
  get 'homepage/index'
  
  root "homepage#index"

  get "/login",
    to: "home#index",
    as: "Home_index"

  get "/diagnoses",
    to: "diagnoses#index",
    as: "Diagnoses_index"

  post "/diagnoses/index",
    to: "diagnoses#result",
    as: "diagnoses_result"

  get "/article",
    to: "articles#user_index",
    as: "user_index_article"

  get "/medicine",
    to: "medicines#user_index",
    as: "user_index_medicine"

  get "/doctor",
    to: "doctors#user_index",
    as: "user_index_doctor"

end

app/models/account.rb
class Account < ApplicationRecord
  # adds virtual attributes for authentication
  has_one :user
  has_one :doctor
  has_many :meeting
  
  # validates email
  validates :username, presence: true, uniqueness: true
  # validates :username, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid username' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :account
  end

app/models/diagnoses.rb
class Diagnoses < ApplicationRecord
    has_many :answer

    validates :answer, presence: true
    validates :answer, uniqueness: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :account
end

app/models/medicine.rb
class Medicine < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord

  belongs_to :account
  
  def create_zoom_meeting(topic)
   zoom_client = Zoom.new
   response = zoom_client.meeting_create(topic: topic, user_id: "Em94MPQZTua6na9XpzRe5A")
   response['join_url']
  end
  def save_zoom_link(meeting_topic)
    return if zoom_link.present?
    _zoom_link = create_zoom_meeting(meeting_topic)
    update(zoom_link: _zoom_link)
  end


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit {broadcast_append_to "rooms"}
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :account
end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_page/_header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="admin.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    
    <title>Admin Page</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body> 
        <header>

              <ul>
                <div class="header-left">
                  <li><%= link_to 'Admin', root_path,  class:"home"  %></li>
                  <li><%= link_to 'Article', articles_path,  class:"btnnav-bar"  %></li>
                  <li><%= link_to 'Medicine', medicines_path,  class:"btnnav-bar"  %></li>
                  <li><%= link_to 'Doctor', doctors_path,  class:"btnnav-bar"  %></li>
                  <li><%= link_to 'User', users_path,  class:"btnnav-bar"  %></li>
                  <li><%= link_to 'Account', accounts_path,  class:"btnnav-bar"  %></li>
                </div>
                <div class="header-right">
                  <li><a class="login" href="/login">Logout</a></li>
                </div>
              </ul>

        </header>

app/views/admin_page/index.html.erb
    <%= render 'header' %> 

    <div class="top-wrapper">
      <div class="top-left">
        <div class="left-welcome">
          <h3>Selamat datang di <span>Telemedicine</span></h3>
          <h4>Lakukan konsultasi online dengan dokter yang terpercaya, bersertifikat dan ahli di bidangnya</h4>
        </div>
      </div>
      <div class="top-right">
        <img <%= image_tag("undraw_doctors_hwty.png",class:"image",height: 800, width: 1100) %>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>